**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

In [7]:
arr_1 = np.array([5, 15, 25, 35, 45])
print(arr_1)

[ 5 15 25 35 45]


In [8]:
arr_zeros = np.zeros(7)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [9]:
arr_ones = np.ones(6)
print(arr_ones)

[1. 1. 1. 1. 1. 1.]


In [11]:
range_arr = np.arange(10,20)
print(range_arr)

[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [12]:
arr_2 = np.array([12, 24, 36, 48, 60])
print(arr_2)

[12 24 36 48 60]


In [22]:
arr_2_mult_2 = arr_2 * 2
print(arr_2_mult_2)

[ 24  48  72  96 120]


In [23]:
arr_2_plus_10 = arr_2 + 10
print(arr_2_plus_10)

[22 34 46 58 70]


In [24]:
arr_2_2 = arr_2 ** 2
print(arr_2_2)

[ 144  576 1296 2304 3600]


In [25]:
arr_2_squered = np.sqrt(arr_2)
print(arr_2_squered)

[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [26]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(data)

[18 27 33 41 52 68 79]


In [27]:
data_mean = data.mean()
print(data_mean)

45.42857142857143


In [28]:
data_min = data.min()
print(data_min)

18


In [30]:
data_max = data.max()
print(data_max)

79


In [31]:
data_sum = data.sum()
print(data_sum)

318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [32]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr)

[15 22 35 44 58 67]


In [33]:
print(arr[0])

15


In [34]:
print(arr[-1])

67


In [35]:
print(arr[1:4])

[22 35 44]


In [36]:
mask = arr > 40
print(arr[mask])

[44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [37]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [38]:
matrix.shape

(3, 3)

In [39]:
print(matrix[0, :])

[2 4 6]


In [48]:
print(matrix[:, 1])

[ 4 10 16]


In [49]:
matrix_sum = matrix.sum()
print(matrix_sum)

90


In [50]:
matrix_mean = matrix.mean()
print(matrix_mean)

10.0
